### ISSUE TITLE
Installation Aborted

### ISSUE THREAD

**Issue by Afriqvist** [ijemafe/PoE-Overlay#1]
![image](https://user-images.githubusercontent.com/1505761/84357475-00972080-abc6-11ea-8bb0-188db0148c4e.png)

For some reason I'm getting Installation Aborted when I'm trying to install "poe-overlay-Setup-0.6.28.exe" What could that be about?

**Comment by Moubai** [comment]
Have you tried to remove poe overlay before to réinstall this one ?
I just did this way, no problem to install it

**Comment by Afriqvist** [comment]
Ah this worked. Thank you!
